# Generated by Django 2.1.5 on 2019-03-03 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text', models.TextField(verbose_name='本文')),
                ('is_public', models.BooleanField(default=True)),
                ('date_birth', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('location', models.CharField(max_length=50, verbose_name='所在地')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ジャンル名')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='webアプリ名')),
                ('text', models.TextField(verbose_name='説明')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('page', models.URLField(verbose_name='URL')),
                ('is_public', models.BooleanField(default=True)),
                ('date_birth', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Subject')),
            ],
        ),
    ]
